@ServiceBus.Emulator.WebApi_HostAddress = https://localhost:56501

POST {{ServiceBus.Emulator.WebApi_HostAddress}}/testSendToQueue
Content-Type: application/json
{
    "queueName": "queue.1"
}

###

POST {{ServiceBus.Emulator.WebApi_HostAddress}}/sendClientCodeToQueue
Content-Type: application/json
{
    "queueName": "queue.1",
    "clientCode": "888999"
}

###

GET {{ServiceBus.Emulator.WebApi_HostAddress}}/peekResponseQueueMessages

###

GET {{ServiceBus.Emulator.WebApi_HostAddress}}/healthz

###