name: ConfigChecker
services:
  configchecker.agent:
    image: ${DOCKER_REGISTRY-}configcheckeragent
    build:
      context: .
      dockerfile: ConfigChecker.Agent/Dockerfile
    ports:
      - "56000:8080"
      - "56001:8081"
    depends_on:
     - emulator
  emulator:
    container_name: "servicebus-emulator"
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    volumes:
      - "${CONFIG_PATH}:/ServiceBus_Emulator/ConfigFiles/Config.json"
    ports:
      - "5672:5672"
    environment:
      SQL_SERVER: sqledge  
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: ${ACCEPT_EULA}
    depends_on:
      - sqledge
    networks:
      sb-emulator:
        aliases:
          - "sb-emulator"
  sqledge:
        container_name: "sqledge"
        image: "mcr.microsoft.com/azure-sql-edge:latest"
        networks:
          sb-emulator:
            aliases:
              - "sqledge"
        environment:
          ACCEPT_EULA: ${ACCEPT_EULA}
          MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
  servicebus.emulator.webapi:
    image: ${DOCKER_REGISTRY-}servicebusemulatorwebapi
    build:
      context: .
      dockerfile: ServiceBus.Emulator.WebApi/Dockerfile
    ports:
     - "56500:8080"
     - "56501:8081"
    depends_on:
     - emulator
    networks:
      sb-emulator:

networks:
  sb-emulator:
