@SecureValueAccessor.WebApi_HostAddress = https://localhost:57001

POST {{SecureValueAccessor.WebApi_HostAddress}}/getRedisValueByKey
Content-Type: application/json
{
    "key": "key1"
}

###

POST {{SecureValueAccessor.WebApi_HostAddress}}/getRedisValueByKey
Content-Type: application/json
{
    "key": "this-should-not-exist"
}

###